select
    patient_id,
    village_id,
    birth_facility_id,
    registration_date as "Date registered",
    registered_by as "Registered by",
    display_id as "{{ translate_string('general.localisedField.displayId.label', var('language'), 'Hospital ID') }}",
    first_name as "{{ translate_string('general.localisedField.firstName.label', var('language'), 'First name') }}",
    last_name as "{{ translate_string('general.localisedField.lastName.label', var('language'), 'Last name') }}",
    date_of_birth as "{{ translate_string('general.localisedField.dateOfBirth.label', var('language'), 'Date of birth') }}",
    sex as "{{ translate_string('general.sex.label', var('language'), 'Sex') }}",
    ethnicity as "{{ translate_string('general.localisedField.ethnicityId.label', var('language'), 'Ethnicity') }}",
    nationality as "{{ translate_string('general.localisedField.nationalityId.label', var('language'), 'Nationality') }}",
    village as "{{ translate_string('general.localisedField.villageId.label', var('language'), 'Village') }}",
    mother as "{{ translate_string('general.localisedField.motherId.label', var('language'), 'Mother') }}",
    father as "{{ translate_string('general.localisedField.fatherId.label', var('language'), 'Father') }}",
    birth_time as "{{ translate_string('general.localisedField.timeOfBirth.label', var('language'), 'Time of birth') }}",
    gestational_age_estimate as "{{ translate_string('general.localisedField.gestationalAgeEstimate.label', var('language'), 'Gestational age (weeks)') }}",
    registered_birth_place as "{{ translate_string('general.localisedField.registeredBirthPlace.label', var('language'), 'Place of birth') }}",
    birth_facility as "{{ translate_string('general.localisedField.birthFacilityId.label', var('language'), 'Name of health facility (if selected)') }}",
    attendant_at_birth as "{{ translate_string('general.localisedField.attendantAtBirth.label', var('language'), 'Attendant at birth') }}",
    name_of_attendant_at_birth as "{{ translate_string('general.localisedField.nameOfAttendantAtBirth.label', var('language'), 'Name of attendant') }}",
    birth_delivery_type as "{{ translate_string('general.localisedField.birthDeliveryType.label', var('language'), 'Delivery type') }}",
    birth_type as "{{ translate_string('general.localisedField.birthType.label', var('language'), 'Single/Plural birth') }}",
    birth_weight as "{{ translate_string('general.localisedField.birthWeight.label', var('language'), 'Birth weight (kg)') }}",
    birth_length as "{{ translate_string('general.localisedField.birthLength.label', var('language'), 'Birth length (cm)') }}",
    apgar_score_one_minute as "{{ translate_string('general.localisedField.apgarScoreOneMinute.label', var('language'), 'Apgar score at 1 min') }}",
    apgar_score_five_minutes as "{{ translate_string('general.localisedField.apgarScoreFiveMinutes.label', var('language'), 'Apgar score at 5 min') }}",
    apgar_score_ten_minutes as "{{ translate_string('general.localisedField.apgarScoreTenMinutes.label', var('language'), 'Apgar score at 10 min') }}"
from {{ ref("ds__births") }}