name: tamanu_source_dbt
version: "2.32.0"
config-version: 2

profile: tamanu_source_dbt

vars:
  language: default
  translation_prefix: report.reporting
  test_patient: h1627394-3778-4c31-a510-9fcb88efdbf3

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - compiled
  - dbt_packages
  - target

models:
  tamanu_source_dbt:
    bases:
      +docs:
        show: true
      +materialized: view
      
    intermediate:
      +materialized: ephemeral
      
    datasets:
      +docs:
        show: false
      +materialized: view
      
    reports:
      +docs:
        show: false
      +tags: [reports, standard]
      
data_tests:
  +docs:
    show: false
  +severity: warn
