name: tamanu_source_dbt
version: "2.31.0"
config-version: 2

profile: tamanu_source_dbt

vars:
  language: en
  translation_prefix: report.reporting
  test_patient: h1627394-3778-4c31-a510-9fcb88efdbf3

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - compiled
  - dbt_packages
  - target

models:
  tamanu_source_dbt:
    bases:
      +docs:
        show: true
      +materialized: view
      +tags:
        [aspen, demoland, fiji, kiribati, nauru, palau, samoa, tonga, tuvalu]

    intermediate:
      +materialized: ephemeral
      +tags:
        [aspen, demoland, fiji, kiribati, nauru, palau, samoa, tonga, tuvalu]

    datasets:
      +docs:
        show: false
      +materialized: view
      fiji:
        +tags: [fiji]
      generic:
        +tags:
          [aspen, demoland, fiji, kiribati, nauru, palau, samoa, tonga, tuvalu]

    reports:
      +docs:
        show: false
      +tags: [reports]
      sql:
        aspen:
          +tags: [aspen]
        fiji:
          +tags: [fiji]
        generic:
          +tags:
            [
              aspen,
              demoland,
              fiji,
              kiribati,
              nauru,
              palau,
              samoa,
              tonga,
              tuvalu,
            ]
        nauru:
          +tags: [nauru]
        palau:
          +tags: [palau]
        samoa:
          +tags: [samoa]
        tuvalu:
          +tags: [tuvalu]
data_tests:
  +docs:
    show: false
  +severity: warn
