name: tamanu_source_dbt
version: "2.20.0"
config-version: 2

profile: tamanu_source_dbt

vars:
  language: en
  date_format: YYYY-MM-DD
  time_format: HH24:MI
  monthyear_format: Mon-YY
  datetime_format: YYYY-MM-DD HH24:MI:SS
  default_start_date: "2020-01-01"
  test_patient: h1627394-3778-4c31-a510-9fcb88efdbf3

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - compiled
  - dbt_packages
  - target

models:
  tamanu_source_dbt:
    bases:
      +materialized: view
      +tags: [fiji, palau, samoa, demoland, kiribati]

    intermediate:
      +materialized: view
      +tags: [fiji, palau, samoa, demoland, kiribati]

    datasets:
      +materialized: view
      fiji:
        +tags: [fiji]
      generic:
        +tags: [fiji, palau, samoa, demoland, kiribati]

    reports:
      +tags: [reports]
      sql:
        fiji:
          +tags: [fiji]
        generic:
          +tags: [fiji, palau, samoa, demoland, kiribati]

data_tests:
  +severity: warn
