[project]
name = "tamanu-source-dbt"
version = "2.38.0"
description = "A dbt project that transforms Tamanu healthcare system data into optimised reporting datasets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.28.0",
    "dbt-core",
    "dbt-postgres",
    "great-expectations==1.5.9",
    "jsonschema",
    "openpyxl>=3.1.0",
    "pandas>=2.0.0",
    "PyYAML>=6.0.1",
    "sqlfluff>=3.0.0",
]

[tool.uv]
package = false
dev-dependencies = []
