import csv
from pathlib import Path

from .dbt_utils import get_deployment_name
from .system_utils import cprint

BASE_DIR = Path.cwd()


def read_csv(rel_path):
    """Read a CSV with stringId and language columns into a nested dict (raw text; literals use repr when emitting)."""
    path = BASE_DIR / rel_path
    if not path.exists():
        return {}
    mapping = {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            string_id = row.get("stringId")
            if not string_id:
                continue
            if string_id not in mapping:
                mapping[string_id] = {}
            for lang, text in row.items():
                if lang != "stringId" and text:
                    mapping[string_id][lang] = text
    return mapping


def generate_translation_macro():
    """
    Generate macros/default_translations.sql from two sources (in priority order):
      1. Standard CSV  — report_translations_standard.csv (default language fallbacks)
      2. Localised CSV — report_translations_{deployment}.csv (deployment-specific overrides)
    """
    deployment = get_deployment_name()

    if deployment == "standard":
        standard = read_csv("report_translations_standard.csv")
        localised = {}
    else:
        standard = read_csv(str(Path("dbt_packages") / "tamanu_source_dbt" / "report_translations_standard.csv"))
        localised = read_csv(f"report_translations_{deployment}.csv")

    # Priority: standard CSV < localised CSV
    merged = standard.copy()
    for string_id, lang_dict in localised.items():
        merged.setdefault(string_id, {}).update(lang_dict)

    macro_content = """{#
Auto-generated macro containing report translations.
Sources (lowest → highest priority):
  1. report_translations_standard.csv       — default language fallbacks
  2. report_translations_{deployment}.csv   — deployment-specific overrides

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_translation_macro.py
#}


{%- macro get_translations() -%}
    {%- set translations = {
"""

    items = sorted(merged.items())
    for i, (string_id, lang_dict) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lang_items = sorted(lang_dict.items())
        # repr() yields valid Jinja/Python string literals (handles ', ", \, newlines, etc.)
        lang_entries = ", ".join([f"{repr(lang)}: {repr(text)}" for lang, text in lang_items])
        macro_content += f"        {repr(string_id)}: {{{lang_entries}}}{comma}\n"

    macro_content += """    } -%}
    {{- return(translations) -}}
{%- endmacro -%}


{%- macro get_default_translations() -%}
    {#- Backwards compatibility: return just default language -#}
    {%- set all_translations = get_translations() -%}
    {%- set default_only = {} -%}
    {%- for string_id, lang_dict in all_translations.items() -%}
        {%- do default_only.update({string_id: lang_dict.get('default', '')}) -%}
    {%- endfor -%}
    {{- return(default_only) -}}
{%- endmacro -%}
"""

    macros_dir = BASE_DIR / "macros"
    macros_dir.mkdir(exist_ok=True)
    filename = "default_translations.sql"

    if deployment != "standard":
        package_standard_macro = BASE_DIR / "dbt_packages" / "tamanu_source_dbt" / "macros" / filename
        if package_standard_macro.exists():
            package_standard_macro.unlink()

    macro_path = macros_dir / filename
    macro_path.write_text(macro_content, encoding="utf-8")

    cprint(
        f"Generated {len(merged)} translations",
        "success",
    )
