import csv
from pathlib import Path

from .dbt_utils import get_deployment_name
from .system_utils import cprint, execute_command_with_output

BASE_DIR = Path.cwd()


def read_csv(rel_path):
    """Read a CSV with stringId and language columns into a nested dict (raw text; literals use repr when emitting)."""
    path = BASE_DIR / rel_path
    if not path.exists():
        return {}
    mapping = {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            string_id = row.get("stringId")
            if not string_id:
                continue
            if string_id not in mapping:
                mapping[string_id] = {}
            for lang, text in row.items():
                if lang != "stringId" and text:
                    mapping[string_id][lang] = text
    return mapping


def read_db_translations():
    """
    Fetch all rows from translated_strings via dbt run-operation and return a
    nested dict of {string_id: {language: text}} (raw text; repr() when writing the macro).

    Uses the get_translations_from_db macro which logs each row as:
        TRANSLATION_DATA:<string_id>~|~<language>~|~<text>

    Returns an empty dict if the dbt command fails, so the caller degrades
    gracefully when no DB connection is available.
    """
    mapping = {}
    cmd = "dbt run-operation get_translations_from_db --profiles-dir config"

    try:
        result = execute_command_with_output(cmd, cwd=BASE_DIR)
        if not result or result.returncode != 0:
            if result:
                cprint(
                    "dbt run-operation failed — skipping database translations",
                    "warning",
                )
            return mapping

        for line in (result.stdout + result.stderr).split("\n"):
            if "TRANSLATION_DATA:" not in line:
                continue
            # maxsplit=2 preserves any ~|~ that appears inside the text value
            parts = line.split("TRANSLATION_DATA:")[1].split("~|~", 2)
            if len(parts) != 3:
                continue
            string_id, language, text = parts[0].strip(), parts[1].strip(), parts[2].strip()
            if not string_id or not language:
                continue
            mapping.setdefault(string_id, {})[language] = text

    except Exception as e:
        cprint(f"Error fetching translations from database: {e}", "error")

    return mapping


def generate_translation_macro():
    """
    Generate macros/default_translations.sql from three sources (in priority order):
      1. Standard CSV  — report_translations_standard.csv (default language fallbacks)
      2. Localised CSV — report_translations_{deployment}.csv (deployment-specific overrides)
      3. Database      — translated_strings table via dbt run-operation (highest priority)
    """
    deployment = get_deployment_name()

    if deployment == "standard":
        standard = read_csv("report_translations_standard.csv")
        localised = {}
    else:
        standard = read_csv(str(Path("dbt_packages") / "tamanu_source_dbt" / "report_translations_standard.csv"))
        localised = read_csv(f"report_translations_{deployment}.csv")

    db_translations = read_db_translations()

    # Priority: standard CSV < localised CSV < database
    merged = standard.copy()
    for string_id, lang_dict in localised.items():
        merged.setdefault(string_id, {}).update(lang_dict)
    for string_id, lang_dict in db_translations.items():
        merged.setdefault(string_id, {}).update(lang_dict)

    macro_content = """{#
Auto-generated macro containing report translations.
Sources (lowest → highest priority):
  1. report_translations_standard.csv       — default language fallbacks
  2. report_translations_{deployment}.csv   — deployment-specific overrides
  3. translated_strings table in the deployment database — all languages

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_translation_macro.py
#}


{%- macro get_translations() -%}
    {%- set translations = {
"""

    items = sorted(merged.items())
    for i, (string_id, lang_dict) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lang_items = sorted(lang_dict.items())
        # repr() yields valid Jinja/Python string literals (handles ', ", \, newlines, etc.)
        lang_entries = ", ".join([f"{repr(lang)}: {repr(text)}" for lang, text in lang_items])
        macro_content += f"        {repr(string_id)}: {{{lang_entries}}}{comma}\n"

    macro_content += """    } -%}
    {{- return(translations) -}}
{%- endmacro -%}


{%- macro get_default_translations() -%}
    {#- Backwards compatibility: return just default language -#}
    {%- set all_translations = get_translations() -%}
    {%- set default_only = {} -%}
    {%- for string_id, lang_dict in all_translations.items() -%}
        {%- do default_only.update({string_id: lang_dict.get('default', '')}) -%}
    {%- endfor -%}
    {{- return(default_only) -}}
{%- endmacro -%}
"""

    macros_dir = BASE_DIR / "macros"
    macros_dir.mkdir(exist_ok=True)
    filename = "default_translations.sql"

    if deployment != "standard":
        package_standard_macro = BASE_DIR / "dbt_packages" / "tamanu_source_dbt" / "macros" / filename
        if package_standard_macro.exists():
            package_standard_macro.unlink()

    macro_path = macros_dir / filename
    macro_path.write_text(macro_content, encoding="utf-8")

    cprint(
        f"Generated {len(merged)} translations",
        "success",
    )
