-- DHIS2 category-option-combos for the disease x age x sex disaggregation of the
-- NCD Indicators report (DHIS2 category combo TlIWfVFnyxW). One row per
-- (disease, age_group, sex). Shared across MSF OCA deployments -- the UIDs are
-- global to the MSF OCA DHIS2 instance (8 diseases x 5 age groups x 3 sex).
-- Built only when var('msf_oca_dhis2') is true. Joined to
-- metric__ncd_indicators on (dhis_ncd_category, age_group, sex).
select * from (
    values
        -- Asthma
        ('epYu6sklgK0', 'asthma', '<5 years', 'Female'),
        ('wXgOa9vg7lX', 'asthma', '<5 years', 'Male'),
        ('RMj4P84zJzL', 'asthma', '<5 years', 'Other/Unknown'),
        ('IkEqqpuNpkj', 'asthma', '5-14 years', 'Female'),
        ('K8dBmAnpaNX', 'asthma', '5-14 years', 'Male'),
        ('U6sAJds63k2', 'asthma', '5-14 years', 'Other/Unknown'),
        ('ecOxE9d42kZ', 'asthma', '15-49 years', 'Female'),
        ('QGXKtGlNz4z', 'asthma', '15-49 years', 'Male'),
        ('CPz7CLM5lZo', 'asthma', '15-49 years', 'Other/Unknown'),
        ('WSFxk9yqAsA', 'asthma', '50+ years', 'Female'),
        ('L3hUvVtuAib', 'asthma', '50+ years', 'Male'),
        ('GEJYVXPZj2n', 'asthma', '50+ years', 'Other/Unknown'),
        ('oTzKHSZXeJ5', 'asthma', 'Unknown age', 'Female'),
        ('Ddn7p8tX3ym', 'asthma', 'Unknown age', 'Male'),
        ('LEvz4kajce8', 'asthma', 'Unknown age', 'Other/Unknown'),

        -- COPD
        ('nDVmSuyP3nV', 'copd', '<5 years', 'Female'),
        ('eMGxS98tqUb', 'copd', '<5 years', 'Male'),
        ('RaYPZGqSxxt', 'copd', '<5 years', 'Other/Unknown'),
        ('rI0hpqfsnkf', 'copd', '5-14 years', 'Female'),
        ('QuhndmuPnVp', 'copd', '5-14 years', 'Male'),
        ('sjQHEnntAAn', 'copd', '5-14 years', 'Other/Unknown'),
        ('vLZe94MAvr7', 'copd', '15-49 years', 'Female'),
        ('EJ6rQ4uVmVF', 'copd', '15-49 years', 'Male'),
        ('skR1Mk8RvSM', 'copd', '15-49 years', 'Other/Unknown'),
        ('p8qzRkbo4nn', 'copd', '50+ years', 'Female'),
        ('VHT2FaohnuR', 'copd', '50+ years', 'Male'),
        ('bZSRM3OAXav', 'copd', '50+ years', 'Other/Unknown'),
        ('OXchO7WwslO', 'copd', 'Unknown age', 'Female'),
        ('M8JmDmAHlNZ', 'copd', 'Unknown age', 'Male'),
        ('RE5Jy3QwxFq', 'copd', 'Unknown age', 'Other/Unknown'),

        -- Diabetes Type 1
        ('gV3OEYJ0S1y', 'diabetes_i', '<5 years', 'Female'),
        ('Sop1A31h14U', 'diabetes_i', '<5 years', 'Male'),
        ('wsmSVR4q8zV', 'diabetes_i', '<5 years', 'Other/Unknown'),
        ('pDnp0Wp5WAE', 'diabetes_i', '5-14 years', 'Female'),
        ('F6okgMYZMFO', 'diabetes_i', '5-14 years', 'Male'),
        ('vq2vXvZBxXa', 'diabetes_i', '5-14 years', 'Other/Unknown'),
        ('CSH0QdiJ73J', 'diabetes_i', '15-49 years', 'Female'),
        ('pIiodF8HHjW', 'diabetes_i', '15-49 years', 'Male'),
        ('JpQlAwBiHqi', 'diabetes_i', '15-49 years', 'Other/Unknown'),
        ('fWDNZ0WRH0y', 'diabetes_i', '50+ years', 'Female'),
        ('NZ1Jqz6iMEd', 'diabetes_i', '50+ years', 'Male'),
        ('FWybAEGbFv2', 'diabetes_i', '50+ years', 'Other/Unknown'),
        ('il51uWeqS7Z', 'diabetes_i', 'Unknown age', 'Female'),
        ('Y1oucSRyRnO', 'diabetes_i', 'Unknown age', 'Male'),
        ('aUcWPWz4pp8', 'diabetes_i', 'Unknown age', 'Other/Unknown'),

        -- Diabetes Type 2
        ('bRqxjmK5dZ5', 'diabetes_ii', '<5 years', 'Female'),
        ('iHf4OpMB50x', 'diabetes_ii', '<5 years', 'Male'),
        ('zzEI5S6kOP0', 'diabetes_ii', '<5 years', 'Other/Unknown'),
        ('fot7hPJFWbK', 'diabetes_ii', '5-14 years', 'Female'),
        ('JKeieWsiqAO', 'diabetes_ii', '5-14 years', 'Male'),
        ('FBkJSHmTwLX', 'diabetes_ii', '5-14 years', 'Other/Unknown'),
        ('Ksr3dKs0q93', 'diabetes_ii', '15-49 years', 'Female'),
        ('UfsyFKUTxmr', 'diabetes_ii', '15-49 years', 'Male'),
        ('V97fyDPH9yV', 'diabetes_ii', '15-49 years', 'Other/Unknown'),
        ('M6Ge07CS19H', 'diabetes_ii', '50+ years', 'Female'),
        ('GfeBKCgOd6g', 'diabetes_ii', '50+ years', 'Male'),
        ('fhWmcrosxIl', 'diabetes_ii', '50+ years', 'Other/Unknown'),
        ('cQZjJ8Jo4h8', 'diabetes_ii', 'Unknown age', 'Female'),
        ('CoaFUU1MNe0', 'diabetes_ii', 'Unknown age', 'Male'),
        ('FuXwF1YqGw0', 'diabetes_ii', 'Unknown age', 'Other/Unknown'),

        -- Epilepsy
        ('IVuXZZMNkkQ', 'epilepsy', '<5 years', 'Female'),
        ('ycwiIbGG0Cd', 'epilepsy', '<5 years', 'Male'),
        ('Nla135TVQ0W', 'epilepsy', '<5 years', 'Other/Unknown'),
        ('XzRZHBpaMz7', 'epilepsy', '5-14 years', 'Female'),
        ('aTjkFkn0dI3', 'epilepsy', '5-14 years', 'Male'),
        ('p4jBuqWpk7s', 'epilepsy', '5-14 years', 'Other/Unknown'),
        ('IkI7VSdputn', 'epilepsy', '15-49 years', 'Female'),
        ('XXqMgfRmamH', 'epilepsy', '15-49 years', 'Male'),
        ('Ghf2M8ymgR2', 'epilepsy', '15-49 years', 'Other/Unknown'),
        ('FZBbDzld4Mk', 'epilepsy', '50+ years', 'Female'),
        ('npmo0GWFUtu', 'epilepsy', '50+ years', 'Male'),
        ('lz1qfaUiHEc', 'epilepsy', '50+ years', 'Other/Unknown'),
        ('pXbqYp9rCq7', 'epilepsy', 'Unknown age', 'Female'),
        ('UACy6uwXAV7', 'epilepsy', 'Unknown age', 'Male'),
        ('Ltv42hSVT5U', 'epilepsy', 'Unknown age', 'Other/Unknown'),

        -- Hypertension
        ('It6RGHv1cNH', 'hypertension', '<5 years', 'Female'),
        ('qxXxoSkUphC', 'hypertension', '<5 years', 'Male'),
        ('fKJuahIvBTF', 'hypertension', '<5 years', 'Other/Unknown'),
        ('Uhy4nti9gAE', 'hypertension', '5-14 years', 'Female'),
        ('u1T3EJvhCyQ', 'hypertension', '5-14 years', 'Male'),
        ('CnfN9KOCpC9', 'hypertension', '5-14 years', 'Other/Unknown'),
        ('ww72UmHBVIR', 'hypertension', '15-49 years', 'Female'),
        ('GRjap3ueFyw', 'hypertension', '15-49 years', 'Male'),
        ('EYSBue227mf', 'hypertension', '15-49 years', 'Other/Unknown'),
        ('CFSZflE5aRd', 'hypertension', '50+ years', 'Female'),
        ('i3fidR3f6UQ', 'hypertension', '50+ years', 'Male'),
        ('nombZ3b2Tqw', 'hypertension', '50+ years', 'Other/Unknown'),
        ('QrH1TGoBcAW', 'hypertension', 'Unknown age', 'Female'),
        ('uPkmn8APiEH', 'hypertension', 'Unknown age', 'Male'),
        ('jfvan7qH4sW', 'hypertension', 'Unknown age', 'Other/Unknown'),

        -- Cardiovascular Disease
        ('ypDE9x5eaxT', 'cvd', '<5 years', 'Female'),
        ('ZcoZTVWj26X', 'cvd', '<5 years', 'Male'),
        ('XVH4FPCp8U9', 'cvd', '<5 years', 'Other/Unknown'),
        ('t9TWiEbYNBH', 'cvd', '5-14 years', 'Female'),
        ('wso6qTQGrbH', 'cvd', '5-14 years', 'Male'),
        ('CZ8YMNPynlZ', 'cvd', '5-14 years', 'Other/Unknown'),
        ('ePbdKRzAC65', 'cvd', '15-49 years', 'Female'),
        ('pOUPk2JiaUm', 'cvd', '15-49 years', 'Male'),
        ('IfW7DAWWgOB', 'cvd', '15-49 years', 'Other/Unknown'),
        ('SsvDtIGEKCo', 'cvd', '50+ years', 'Female'),
        ('JW7rgpAyUI4', 'cvd', '50+ years', 'Male'),
        ('WYxJ2RArJvJ', 'cvd', '50+ years', 'Other/Unknown'),
        ('EeRjFSJLGhL', 'cvd', 'Unknown age', 'Female'),
        ('tjV6f8CGri9', 'cvd', 'Unknown age', 'Male'),
        ('RFDq8RC3Pbp', 'cvd', 'Unknown age', 'Other/Unknown'),

        -- Other NCD
        ('de6h7INszm4', 'other_ncd', '<5 years', 'Female'),
        ('KGerfsWnYt2', 'other_ncd', '<5 years', 'Male'),
        ('LEFuBzrEbnJ', 'other_ncd', '<5 years', 'Other/Unknown'),
        ('Ilpdr0Sq6XH', 'other_ncd', '5-14 years', 'Female'),
        ('VdlMCsMygNs', 'other_ncd', '5-14 years', 'Male'),
        ('kZbWCpuPVIA', 'other_ncd', '5-14 years', 'Other/Unknown'),
        ('Wjjq9HmiWmv', 'other_ncd', '15-49 years', 'Female'),
        ('V8NbwyFhLsX', 'other_ncd', '15-49 years', 'Male'),
        ('L85G9q9HUbE', 'other_ncd', '15-49 years', 'Other/Unknown'),
        ('v6UXXAUkQdY', 'other_ncd', '50+ years', 'Female'),
        ('MibtiDbh2kT', 'other_ncd', '50+ years', 'Male'),
        ('KeKK9JwXyR4', 'other_ncd', '50+ years', 'Other/Unknown'),
        ('Yjhwa0Ha3Al', 'other_ncd', 'Unknown age', 'Female'),
        ('YprO2Pxqxmj', 'other_ncd', 'Unknown age', 'Male'),
        ('l9VUOXsuFaq', 'other_ncd', 'Unknown age', 'Other/Unknown')
) as t(id, dhis_ncd_category, age_group, sex)
