tamanu_source_dbt:
  target: demo
  outputs:
    demo:
      type: postgres
      threads: 1
      host: "{{ env_var('TAMANU_DEMO_DB_URL') }}"
      port: "{{ env_var('TAMANU_DEMO_DB_PORT') | as_number }}"
      user: "{{ env_var('TAMANU_DEMO_DB_USER') }}"
      pass: "{{ env_var('TAMANU_DEMO_DB_PASSWORD') }}"
      dbname: "{{ env_var('TAMANU_DEMO_DB_DATABASE') }}"
      schema: reporting
    release:
      type: postgres
      threads: 1
      host: "{{ env_var('TAMANU_RL_DB_URL') }}"
      port: "{{ env_var('TAMANU_RL_DB_PORT') | as_number }}"
      user: "{{ env_var('TAMANU_RL_DB_USER') }}"
      pass: "{{ env_var('TAMANU_RL_DB_PASSWORD') }}"
      dbname: "{{ env_var('TAMANU_RL_DB_DATABASE') }}"
      schema: reporting
