select
    patient_id,
    title,
    marital_status,
    primary_contact_number,
    secondary_contact_number,
    emergency_contact_name,
    emergency_contact_number,
    social_media,
    ethnicity_id,
    religion_id,
    nationality_id,
    secondary_village_id,
    country_id,
    division_id,
    subdivision_id,
    medical_area_id,
    nursing_zone_id,
    settlement_id,
    city_town,
    street_village,
    country_of_birth_id,
    place_of_birth,
    birth_certificate,
    driving_license,
    passport,
    educational_level,
    occupation_id,
    blood_type,
    patient_billing_type_id,
    health_center_id,
    insurer_id,
    insurer_policy_number,
    mother_id,
    father_id,
    registered_by_id,
    updated_at_by_field as updated_by_field,
    created_at::date as registration_date
from {{ source("tamanu", "patient_additional_data") }}
where deleted_at is null
    and id != '{{ var("test_patient") }}'
