SELECT
    id,
    manner,
    recent_surgery AS had_recent_surgery,
    last_surgery_date,
    last_surgery_reason_id,
    external_cause_date,
    external_cause_location,
    external_cause_notes,
    was_pregnant,
    pregnancy_contributed,
    fetal_or_infant AS was_fetal_or_infant,
    stillborn AS was_stillborn,
    birth_weight,
    within_day_of_birth AS was_within_day_of_birth,
    hours_survived_since_birth,
    carrier_age,
    carrier_pregnancy_weeks,
    carrier_existing_condition_id,
    outside_health_facility AS was_outside_health_facility,
    primary_cause_time_after_onset,
    primary_cause_condition_id,
    antecedent_cause1_time_after_onset,
    antecedent_cause1_condition_id,
    antecedent_cause2_time_after_onset,
    antecedent_cause2_condition_id,
    antecedent_cause3_time_after_onset,
    antecedent_cause3_condition_id,
    patient_id,
    clinician_id AS recorded_by_id,
    facility_id,
    is_final,
    visibility_status
FROM {{ source("tamanu", "patient_death_data") }}
WHERE deleted_at IS NULL
    AND patient_id != 'h1627394-3778-4c31-a510-9fcb88efdbf3'
