import sys
import os
import csv

from utils import get_deployment_name


BASE_DIR = os.getcwd()

# Column order is fixed by the macro/model contract — keep in sync with
# metric_definitions.yml and the canonical schema (data architecture D5).
COLUMNS = [
    "metric_id",
    "kind",
    "name",
    "description",
    "numerator_description",
    "denominator_description",
    "data_source",
    "definition_source",
    "definition_source_code",
    "definition_rationale",
    "unit",
    "subject_grain",
    "disaggregations",
    "variant_of",
    "owner",
    "status",
    "spec_path",
]


def read_csv(rel_path):
    """Read a metric_definitions CSV into a dict keyed by metric_id."""
    path = os.path.join(BASE_DIR, rel_path)
    if not os.path.exists(path):
        return {}
    rows = {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            metric_id = (row.get("metric_id") or "").strip()
            if not metric_id:
                continue
            rows[metric_id] = {col: (row.get(col) or "").strip() for col in COLUMNS}
    return rows


def merge_definitions(standard, localised):
    """Merge localised rows over standard, keyed on metric_id (localised wins)."""
    merged = dict(standard)
    merged.update(localised)
    return merged


def sql_literal(value):
    """Render a CSV cell as a SQL literal — empty cells become NULL, others quoted text."""
    if value == "":
        return "null"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def build_macro_content(definitions):
    """Render the macro source for a dict of metric definitions, sorted by metric_id."""
    rows = sorted(definitions.values(), key=lambda r: r["metric_id"])

    # Cast every column to text — a VALUES column that is NULL in all rows is
    # otherwise typed `unknown`, which fails when the model materialises as a view.
    select_list = ",\n".join(f"    {col}::text as {col}" for col in COLUMNS)
    column_aliases = ",\n        ".join(COLUMNS)

    value_rows = []
    for row in rows:
        cells = ", ".join(sql_literal(row[col]) for col in COLUMNS)
        value_rows.append(f"        ({cells})")
    values_block = ",\n".join(value_rows)

    return f"""{{#
Auto-generated macro containing the canonical metric definitions registry.
Generated from csv/metric_definitions.csv and any deployment-specific extension.

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_metric_definitions_macro.py
#}}


{{%- macro get_metric_definitions() -%}}
select
{select_list}
from (
    values
{values_block}
) as md (
        {column_aliases}
)
{{%- endmacro -%}}
"""


def generate_metric_definitions_macro():
    """Read the metric definitions CSV(s) and generate a macro emitting a VALUES relation."""
    deployment = get_deployment_name()

    if deployment == "standard":
        standard = read_csv(os.path.join("csv", "metric_definitions.csv"))
        localised = {}
    else:
        standard = read_csv(
            os.path.join(
                "dbt_packages", "tamanu_source_dbt", "csv", "metric_definitions.csv"
            )
        )
        localised = read_csv(os.path.join("csv", f"metric_definitions_{deployment}.csv"))

    merged = merge_definitions(standard, localised)
    macro_content = build_macro_content(merged)

    macros_dir = os.path.join(BASE_DIR, "macros")
    os.makedirs(macros_dir, exist_ok=True)
    macro_path = os.path.join(macros_dir, "metric_definitions.sql")

    if deployment != "standard":
        package_macro = os.path.join(
            BASE_DIR,
            "dbt_packages",
            "tamanu_source_dbt",
            "macros",
            "metric_definitions.sql",
        )
        if os.path.exists(package_macro):
            os.remove(package_macro)

    with open(macro_path, "w", encoding="utf-8") as f:
        f.write(macro_content)

    print(f"Generated {macro_path}")
    print(f"Loaded {len(merged)} metric definitions (standard + localised)")


if __name__ == "__main__":
    try:
        generate_metric_definitions_macro()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
