import sys
import os

import yaml


BASE_DIR = os.getcwd()

# Column order is fixed by the macro/model contract — keep in sync with
# models/metric_definitions.yml and the canonical schema (data architecture D5).
# Authored in documentations/metrics/*.yml.
COLUMNS = [
    "metric_id",
    "kind",
    "name",
    "description",
    "numerator_description",
    "denominator_description",
    "data_source",
    "definition_source",
    "definition_source_code",
    "definition_rationale",
    "unit",
    "subject_grain",
    "disaggregations",
    "variant_of",
    "owner",
    "status",
    "spec_path",
]


# Columns authored as YAML lists; rendered to the comma-joined text the macro emits.
LIST_COLUMNS = {"disaggregations"}


def _cell(column, value):
    """Normalise one authored value to the string the macro renders."""
    if value is None:
        return ""
    if column in LIST_COLUMNS and isinstance(value, list):
        return ",".join(str(v).strip() for v in value if str(v).strip())
    return str(value).strip()


def read_definitions(rel_path):
    """Read a metric_definitions YAML into a dict keyed by metric_id."""
    path = os.path.join(BASE_DIR, rel_path)
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        loaded = yaml.safe_load(f) or {}
    rows = {}
    for entry in loaded.get("metrics") or []:
        metric_id = _cell("metric_id", entry.get("metric_id"))
        if not metric_id:
            continue
        rows[metric_id] = {col: _cell(col, entry.get(col)) for col in COLUMNS}
    return rows


def read_definitions_dir(rel_dir):
    """Read every *.yml in a metrics directory, merged by metric_id.

    The split into files is presentational — one per programme — so an id defined
    twice is an authoring mistake and raises rather than letting one file quietly
    win on filesystem order.
    """
    directory = os.path.join(BASE_DIR, rel_dir)
    if not os.path.isdir(directory):
        return {}
    rows = {}
    origin = {}
    for filename in sorted(os.listdir(directory)):
        if not filename.endswith((".yml", ".yaml")):
            continue
        for metric_id, row in read_definitions(os.path.join(rel_dir, filename)).items():
            if metric_id in rows:
                raise ValueError(
                    f"metric_id {metric_id!r} is defined in both "
                    f"{origin[metric_id]} and {filename}"
                )
            rows[metric_id] = row
            origin[metric_id] = filename
    return rows


def sql_literal(value):
    """Render a registry value as a SQL literal — empty becomes NULL, others quoted text."""
    if value == "":
        return "null"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def build_macro_content(definitions):
    """Render the macro source for a dict of metric definitions, sorted by metric_id."""
    # An empty registry renders `values` with no row tuples, which is invalid SQL that
    # only fails much later at `dbt run`. Fail here, where the cause is still visible.
    if not definitions:
        raise ValueError(
            "no metric definitions found -- refusing to write a macro with an empty "
            "VALUES clause. Check that documentations/metrics/*.yml is readable from "
            "the current directory, and in a deployment repo that dbt deps has "
            "vendored tamanu_source_dbt."
        )

    rows = sorted(definitions.values(), key=lambda r: r["metric_id"])

    # Cast every column to text — a VALUES column that is NULL in all rows is
    # otherwise typed `unknown`, which fails when the model materialises as a view.
    select_list = ",\n".join(f"    {col}::text as {col}" for col in COLUMNS)
    column_aliases = ",\n        ".join(COLUMNS)

    value_rows = []
    for row in rows:
        cells = ", ".join(sql_literal(row[col]) for col in COLUMNS)
        value_rows.append(f"        ({cells})")
    values_block = ",\n".join(value_rows)

    return f"""{{#
Auto-generated macro containing the canonical metric definitions registry.
Generated from documentations/metrics/*.yml -- every metric is defined in tamanu-source-dbt.

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_metric_definitions_macro.py
#}}


{{%- macro get_metric_definitions() -%}}
select
{select_list}
from (
    values
{values_block}
) as md (
        {column_aliases}
)
{{%- endmacro -%}}
"""


def generate_metric_definitions_macro():
    """Read the metric definitions YAML(s) and generate a macro emitting a VALUES relation."""
    # Imported lazily so the pure helpers above stay importable (e.g. by unit
    # tests) without pulling in the heavier utils dependency chain.
    from utils import get_deployment_name

    deployment = get_deployment_name()

    # Every metric is defined in tamanu-source-dbt, so there is one source of
    # definitions: this repo's own registry, or the package's when generating
    # inside a deployment repo. A deployment contributes no definitions of its own.
    if deployment == "standard":
        registry_dir = os.path.join("documentations", "metrics")
    else:
        registry_dir = os.path.join(
            "dbt_packages", "tamanu_source_dbt", "documentations", "metrics"
        )

    definitions = read_definitions_dir(registry_dir)
    macro_content = build_macro_content(definitions)

    macros_dir = os.path.join(BASE_DIR, "macros")
    os.makedirs(macros_dir, exist_ok=True)
    macro_path = os.path.join(macros_dir, "metric_definitions.sql")

    if deployment != "standard":
        package_macro = os.path.join(
            BASE_DIR,
            "dbt_packages",
            "tamanu_source_dbt",
            "macros",
            "metric_definitions.sql",
        )
        if os.path.exists(package_macro):
            os.remove(package_macro)

    with open(macro_path, "w", encoding="utf-8") as f:
        f.write(macro_content)

    print(f"Generated {macro_path}")
    print(f"Loaded {len(definitions)} metric definitions")


if __name__ == "__main__":
    try:
        generate_metric_definitions_macro()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
