import sys
import os
import csv

from utils import get_deployment_name


BASE_DIR = os.getcwd()


def read_csv(rel_path):
    """Read a CSV with stringId and language columns into a nested dict, escaping quotes for Jinja."""
    path = os.path.join(BASE_DIR, rel_path)
    if not os.path.exists(path):
        return {}
    mapping = {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            string_id = row.get("stringId")
            if not string_id:
                continue

            # Initialize nested dict for this string_id if not exists
            if string_id not in mapping:
                mapping[string_id] = {}

            # Add all language columns (skip stringId column)
            for lang, text in row.items():
                if lang != "stringId" and text:
                    text_escaped = text.replace("\\", "\\\\").replace("'", "\\'")
                    mapping[string_id][lang] = text_escaped
    return mapping


def validate_no_default_for_standard_strings(localised, standard):
    """Error if project CSV defines 'default' for a stringId that already exists in standard."""
    errors = [
        string_id
        for string_id, lang_dict in localised.items()
        if string_id in standard and "default" in lang_dict
    ]
    if errors:
        print(
            "Error: the following stringIds have a 'default' translation in the project CSV\n"
            "but are already defined in tamanu-source-dbt standard translations.\n"
            "Project CSVs should only add language-specific translations (e.g. 'en') for standard stringIds:"
        )
        for sid in sorted(errors):
            print(f"  - {sid}")
        sys.exit(1)


def generate_translation_macro():
    """Read CSV and generate a macro file with translations as a dictionary."""
    deployment = get_deployment_name()

    if deployment == "standard":
        standard = read_csv("report_translations_standard.csv")
        localised = {}
    else:
        standard = read_csv(
            os.path.join(
                "dbt_packages", "tamanu_source_dbt", "report_translations_standard.csv"
            )
        )
        localised = read_csv(f"report_translations_{deployment}.csv")
        validate_no_default_for_standard_strings(localised, standard)

    # Merge standard and localised translations
    # For each string_id, merge language dicts with localised overriding standard
    merged = standard.copy()
    for string_id, lang_dict in localised.items():
        merged.setdefault(string_id, {}).update(lang_dict)

    macro_content = """{#
Auto-generated macro containing report translations.
Generated from report_translations_standard.csv and project-specific translations.

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_translation_macro.py
#}


{%- macro get_translations() -%}
    {%- set translations = {
"""

    # Add each translation as a nested dictionary entry
    items = sorted(merged.items())
    for i, (string_id, lang_dict) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""

        # Build the language dict string
        lang_items = sorted(lang_dict.items())
        lang_entries = ", ".join([f"'{lang}': '{text}'" for lang, text in lang_items])

        macro_content += f"        '{string_id}': {{{lang_entries}}}{comma}\n"

    macro_content += """    } -%}
    {{- return(translations) -}}
{%- endmacro -%}


{%- macro get_default_translations() -%}
    {#- Backwards compatibility: return just default language -#}
    {%- set all_translations = get_translations() -%}
    {%- set default_only = {} -%}
    {%- for string_id, lang_dict in all_translations.items() -%}
        {%- do default_only.update({string_id: lang_dict.get('default', '')}) -%}
    {%- endfor -%}
    {{- return(default_only) -}}
{%- endmacro -%}
"""

    macros_dir = os.path.join(BASE_DIR, "macros")
    os.makedirs(macros_dir, exist_ok=True)
    filename = "translation.sql"

    if deployment != "standard":
        package_standard_macro = os.path.join(
            BASE_DIR,
            "dbt_packages",
            "tamanu_source_dbt",
            "macros",
            "translation.sql",
        )
        if os.path.exists(package_standard_macro):
            os.remove(package_standard_macro)

    # Remove old default_translations.sql if it exists (renamed to translation.sql in v2.52).
    # TODO: remove this block once all tamanu-dbt-* repos are on at least v2.52.
    old_macro_path = os.path.join(macros_dir, "default_translations.sql")
    if os.path.exists(old_macro_path):
        os.remove(old_macro_path)

    macro_path = os.path.join(macros_dir, filename)

    with open(macro_path, "w", encoding="utf-8") as f:
        f.write(macro_content)

    print(f"Generated {macro_path}")
    print(f"Loaded {len(merged)} translations (standard + localised)")


if __name__ == "__main__":
    try:
        generate_translation_macro()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
