import sys
import os
import csv

from utils import get_deployment_name


BASE_DIR = os.getcwd()


def read_csv(rel_path):
    """Read a CSV of stringId,default into a dict, escaping quotes for Jinja."""
    path = os.path.join(BASE_DIR, rel_path)
    if not os.path.exists(path):
        return {}
    mapping = {}
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            string_id = row.get("stringId")
            text = row.get("default")
            if string_id and text is not None:
                text_escaped = text.replace("\\", "\\\\").replace("'", "\\'")
                mapping[string_id] = text_escaped
    return mapping


def generate_translation_macro():
    """Read CSV and generate a macro file with translations as a dictionary."""
    deployment = get_deployment_name()

    if deployment == "standard":
        standard = read_csv("report_translations_standard.csv")
        localised = {}
    else:
        standard = read_csv(
            os.path.join(
                "dbt_packages", "tamanu_source_dbt", "report_translations_standard.csv"
            )
        )
        localised = read_csv("report_translations_localised.csv")

    merged = {}
    merged.update(standard)
    merged.update(localised)

    macro_content = """{#
Auto-generated macro containing default report translations.
Generated from report_translations_standard.csv

DO NOT EDIT THIS FILE MANUALLY!
Run: python scripts/generate_translation_macro.py
#}


{%- macro get_default_translations() -%}
    {%- set translations = {
"""

    # Add each translation as a dictionary entry
    items = sorted(merged.items())
    for i, (string_id, text) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        macro_content += f"        '{string_id}': '{text}'{comma}\n"

    macro_content += """    } -%}
    {{- return(translations) -}}
{%- endmacro -%}
"""

    macros_dir = os.path.join(BASE_DIR, "macros")
    os.makedirs(macros_dir, exist_ok=True)
    filename = "default_translations.sql"

    if deployment != "standard":
        package_standard_macro = os.path.join(
            BASE_DIR,
            "dbt_packages",
            "tamanu_source_dbt",
            "macros",
            "default_translations.sql",
        )
        if os.path.exists(package_standard_macro):
            os.remove(package_standard_macro)

    macro_path = os.path.join(macros_dir, filename)

    with open(macro_path, "w", encoding="utf-8") as f:
        f.write(macro_content)

    print(f"Generated {macro_path}")
    print(f"Loaded {len(merged)} translations (standard + localised)")


if __name__ == "__main__":
    try:
        generate_translation_macro()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
