-- with reporting_months as (
--     select month::date
--     from generate_series(
--         concat(left( {{ parameter('fromDate', default_value='2024-01-01', data_type='text') }}, 7), '-01')::date,
--         concat(left( {{ parameter('toDate', default_value='2024-01-01', data_type='text') }}, 7), '-01')::date,
--         '1 month'::interval
--     ) month
-- ),

-- area_capacity as (
--     select 
--         l.location_group_id,
--         sum(l.max_occupancy) as capacity
--     from {{ ref('locations') }} l
--     group by l.location_group_id
-- ),

-- area_occupancy as (
--     select
--         rm.month,
--         alo.facility_id,
--         alo.location_group_id,
--         max(ac.capacity) as capacity,
--         sum(alo.occupancy) as occupancy,
--         round(sum(alo.occupancy) / (
--             max(ac.capacity)
--             * case
--                 when rm.month > (current_date - '1 month'::interval) then current_date - rm.month
--                 else (rm.month + '1 month'::interval)::date - rm.month
--             end
--         ) * 100, 1) as occupancy_rate
--     from reporting_months rm
--     join {{ ref('int__admission_location_occupancy') }} alo
--         on alo.date::date between rm.month and (rm.month + '1 month'::interval - '1 day'::interval)
--     join area_capacity ac on ac.location_group_id = alo.location_group_id
--     group by rm.month, alo.facility_id, alo.location_group_id
-- ),

-- area_summary as (
--     select
--         rm.month,
--         alh.facility_id,
--         alh.location_group_id,
--         count(*) filter (where alh.admission) as admissions,
--         count(*) filter (where alh.discharge) as discharges,
--         count(*) filter (where alh.death) as deaths,
--         count(*) filter (where alh.transfer_in) as transfer_ins,
--         count(*) filter (where alh.transfer_out) as transfer_outs,
--         round(avg(alh.length_of_stay), 1) as avg_length_of_stay
--     from reporting_months rm
--     join {{ ref('int__admission_location_history') }} alh
--         on alh.date::date between rm.month and (rm.month + '1 month'::interval - '1 day'::interval)
--     group by
--         rm.month,
--         alh.facility_id,
--         alh.location_group_id
-- )

-- select
--     to_char(rm.month, '{{ var("monthyear_format") }}') as "{{ translate_string('', 'Month') }}",
--     f.name as "{{ translate_string('general.localisedField.facility.label', 'Facility') }}",
--     lg.name as "{{ translate_string('general.localisedField.area.label', 'Area') }}",
--     coalesce(sa.admissions, 0) as "{{ translate_string('', 'Number of admissions') }}",
--     coalesce(sa.discharges, 0) as "{{ translate_string('', 'Number of discharges') }}",
--     coalesce(sa.deaths, 0) as "{{ translate_string('', 'Number of deaths') }}",
--     coalesce(sa.transfer_ins, 0) as "{{ translate_string('', 'Number of transfers into location') }}",
--     coalesce(sa.transfer_outs, 0) as "{{ translate_string('', 'Number of transfers out of location') }}",
--     coalesce(sa.avg_length_of_stay, 0) as "{{ translate_string('', 'Average length of stay') }}",
--     coalesce(ao.occupancy, 0) as "{{ translate_string('', 'Number of patient days') }}",
--     coalesce(ao.capacity, 0) as "{{ translate_string('', 'Number of beds') }}",
--     case
--         when ao.occupancy_rate notnull then concat(ao.occupancy_rate, '%') else 'N/A'
--     end as "{{ translate_string('', 'Bed occupancy (%)') }}"
-- from reporting_months rm
-- left join area_summary sa
--     on sa.month = rm.month
-- left join area_occupancy ao
--     on ao.month = rm.month
--     and (ao.facility_id = sa.facility_id or sa.facility_id is null)
--     and (ao.location_group_id = sa.location_group_id or sa.location_group_id is null)
-- join {{ ref('location_groups') }} lg on lg.id = coalesce(sa.location_group_id, ao.location_group_id)
-- join {{ ref('facilities') }} f on f.id = lg.facility_id
-- where sa.facility_id notnull or ao.facility_id notnull
--     and case
--         when {{ parameter('locationGroupId') }} is null then true
--         else lg.id::text = {{ parameter('locationGroupId') }}
--     end
-- order by rm.month, sa.facility_id, lg.id
