version: 2

sources:
  - name: tamanu
    schema: public
    description: "Tamanu source database"
    tables:
      - name: settings
        description: ""
        columns:
          - name: id
            data_type: UUID
            description: ""
          - name: created_at
            data_type: TIMESTAMP WITH TIME ZONE
            description: ""
          - name: updated_at
            data_type: TIMESTAMP WITH TIME ZONE
            description: ""
          - name: deleted_at
            data_type: TIMESTAMP WITH TIME ZONE
            description: ""
          - name: key
            data_type: TEXT
            description: ""
          - name: value
            data_type: JSONB
            description: ""
          - name: facility_id
            data_type: CHARACTER VARYING(255)
            description: ""
          - name: updated_at_sync_tick
            data_type: BIGINT
            description: ""
