name: Docs

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  deploy:
    name: "${{ github.event_name == 'push' && 'Deploy' || 'Check' }} docs"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for AWS login
    env:
      BUCKET: s3://bes-data-docs
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::491618206332:role/gha-dbt-docs
          role-session-name: GithubActionsTamanuSourceDbtDocs

      - name: Prepare database config
        uses: actions/github-script@v6
        with:
          script: |
            const prefix = 'TAMANU_SOURCE_DB';
            core.exportVariable('ENV_DB_PREFIX', prefix);
            core.exportVariable(`${prefix}_DATABASE`, 'tamanu_source');

      - name: Retrieve tamanu database credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          parse-json-secrets: true
          secret-ids: "${{ env.ENV_DB_PREFIX }}, ${{ vars.REPLICAS_DB_SECRET_ARN }}"

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-secret: ${{ secrets.TAILSCALE_DBPROXY_ACCESS_OAUTH }}
          tags: tag:infra,tag:infra-gha-deploy

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dbt
        run: pip3 install dbt-{postgres,duckdb}

      - name: Configure dbt
        run: |
          set -euxo pipefail
          dbt deps --profiles-dir ./config

      - name: Build docs
        run: dbt docs generate --profiles-dir ./config

      - name: Prepare upload
        run: |
          set -euxo pipefail
          mkdir -p upload
          cp target/{manifest,catalog}.json target/index.html upload/
          ls -shal upload/

      ## only upload on pushes

      - name: Upload to latest
        if: github.event_name == 'push' && github.ref_type == 'branch'
        run: aws s3 cp upload/ $BUCKET/tamanu-source-dbt/latest/ --recursive

      - name: Upload to version
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: aws s3 cp upload/ $BUCKET/tamanu-source-dbt/${{ github.ref_name }}/ --recursive
